=== IbaiG04/IbaiG04.github.io/albisteak.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="berriak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="albistea" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="izenburua" type="xs:string" />
                            <xs:element name="edukia" type="xs:string" />
                            <xs:element name="linkimg" type="xs:string" />
                            <xs:element name="data" type="xs:string" />
                            <xs:element name="idazlea" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== IbaiG04/IbaiG04.github.io/albisteak.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="albisteak.xsl"?>

<berriak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="albisteak.xsd">
    <albistea>
        <izenburua>Airsoft ofizialki kirol izendatu dute 2024ko Pariseko Olinpiar Jokoetan</izenburua>
        <edukia>Airsoftek mugarri historikoa lortu du kirol gisa izan duen bilakaeran, ofizialki kirol gisa onartua izan baita 2024ko Pariseko Joko Olinpikoetan. Nazioarteko Batzorde Olinpikoak kirol olinpikoaren estatusa eman dio Airsofti, eta horrek esan nahi du Airsofteko jokalariek aukera dutela orain euren herrialdeak munduko txapelketarik handienean ordezkatzeko. Lorpen horrek Airsoften ikusgarritasuna eta ospea ere areagotu ditu mundu osoan.</edukia>
        <linkimg>media/img.png</linkimg>
        <data>23/01/2023 - 10:45</data>
        <idazlea>Irkus</idazlea>
    </albistea>
    <albistea>
        <izenburua>Airsoft ofizialki kirol izendatu dute 2024ko Pariseko Olinpiar Jokoetan</izenburua>
        <edukia>Airsoftek mugarri historikoa lortu du kirol gisa izan duen bilakaeran, ofizialki kirol gisa onartua izan baita 2024ko Pariseko Joko Olinpikoetan. Nazioarteko Batzorde Olinpikoak kirol olinpikoaren estatusa eman dio Airsofti, eta horrek esan nahi du Airsofteko jokalariek aukera dutela orain euren herrialdeak munduko txapelketarik handienean ordezkatzeko. Lorpen horrek Airsoften ikusgarritasuna eta ospea ere areagotu ditu mundu osoan.</edukia>
        <linkimg>media/img.png</linkimg>
        <data>23/01/2023 - 10:45</data>
        <idazlea>Irkus</idazlea>
    </albistea>
</berriak>
